import Head from 'next/head'
import SearchBar from '../components/SearchBar'
import Coins from '../components/Coins'

export default function Home({coins}) {
  return (
    <div >
      <Head>
        <title>Crypto Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchBar/>
      <Coins coins={coins}/>
    </div>
  )
}

export const getServerSideProps = async() =>{
  const res = await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false')
  const coins = await res.json()
  return{
    props:{
      coins
    }
  }

}